name: Ping URL
description: "Ping URL until maximum trials have exceeded. If result is not 200 until then, fails the action."


inputs:
  url:
    required: true
    description: URL to ping
  max_trials:
    required: false
    description: Maximum number of trials until action fails
    default: '10'
  delay:
    required: true
    description: Delay in seconds between trials
    default: '10'

runs:
  using: docker
  image: ./.github/actions/docker-ping-url/bun-server/Dockerfile


