name: Ping URL
description: "Ping URL until maximum trials have exceeded. If result is not 200 until then, fails the action."

inputs:
  docker_username:
    required: true
    description: docker username
  docker_token:
    required: true
    description: docker token

runs:
  using: composite
  steps:
    - name: login docker
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: '/.github/actions/docker-ping-url/Dockerfile'
        push: true
        tags: bun-js:latest