name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs:
  node-version:
    description: "NodeJS version to use"
    required: true
    default: 20.x
  working-dir:
    required: false
    description: "The working directory of the application"
    default: "."
runs:
  using: composite
  steps:
    - name: Setup NodeJS version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
       path: |
         ${{ inputs.working-dir }}/node_modules
         ${{ inputs.working-dir }}/package.json
       key: ${{ runner.os }}-myApp-${{ hashFiles(inputs.working-dir + '/package-lock.json')}}
       restore-keys: |
            ${{ runner.os }}-myApp-

    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-dir }}
      run: |
        npm install