name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs:
  node-version:
    description: "NodeJS version to use"
    required: true
    default: 20.x
  working-dir:
    required: false
    description: "The working directory of the application"
    default: "."
  target-env:
    description:  Controls whether dev dependencies are installed
    required: false
    default: dev

runs:
  using: composite
  steps:
    - name: echo variables
      shell: bash
      run: |
        echo "working-dir: ${{ inputs.working-dir }}"
    - name: Setup NodeJS version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.working-dir }}/node_modules
        key: ${{ runner.os }}-myApp-${{ inputs.target-env }}-${{ hashFiles('inputs.working-dir/package-lock.json')}}
        restore-keys: |
          ${{ runner.os }}-myApp-${{ inputs.target-env }}-${{ hashFiles('inputs.working-dir/package-lock.json')}}

    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-dir }}
      run: |
         npm ci ${{ inputs.target-env == 'dev' &&  || '--omit=dev' }}
