name: Docker ping url
description: Docker runs and ping url with trials
inputs:
  url:
    description: "The URL to ping"
    required: true
  max_trials:
    description: "Maximum number of ping trials"
    required: true
    default: "10"
  delay:
    description: "Delay between pings in seconds"
    required: true
    default: "1"
runs:
  using: docker
  image: Dockerfile