name: event-workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, reopened]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
     environment:
       description: "Env against to run"
       type: environment
       required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{github.event_name}}"
