name: event-workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, reopened]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
     myInput:
        default: myInput
     environment:
       description: "Env against to run"
       type: environment
       required: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{github.event_name}}"
          echo " get the value from work_dispatcher : ${{inputs.myInput}}"
