name: 03 workflow runners
on:
    push:
    workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name : Show OS
        shell: bash
        run: |
          echo "i am on  ubuntu bash"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name : Show OS
        shell: bash
        run: |
          echo "i am on windows bash"
  macos-echo:
    runs-on: macos-latest
    steps:
      - name : Show OS
        shell: bash
        run: |
          echo "i am on macos bash"