name: 05 - 1 - Event Filters and Activity Types
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'
      - 'releases/**'
jobs:
  print_message:
    runs-on: ubuntu-latets
    steps:
      - name: echo the values
        run: |
          echo " Running whenever a PR is opened or synchronized AND base branch is main"