name: 06 - Contexts
run-name: 06 - context - cutome name - ${{inputs.info}}
on:
    push:
    workflow_dispatch:
        inputs:
          info:
            description: 'test the env'
            type: string
            required: true
            default: 'Info'
env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'
  MY_NAME: 'Jayaram'
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
         echo "event Name : ${{github.event_name}}"
         echo "Ref: ${{github.ref}}"
         echo "SHA: ${{github.sha}}"
         echo "Actor: ${{github.actor}}"
         echo "workflow: ${{github.workflow}}"
         echo "RunId: ${{github.run_id}}"
         echo "RunNumber: ${{github.run_number}}"
         echo " get the env varaiable"
         echo "workflow variable: ${{env.MY_WORKFLOW_VAR}}
         echo "workflow myName: ${{env.MY_NAME}}
      - name: Retrieve Variable
        run: |
          echo "Repo variable : ${{vars.MY_REPO_VAR}}"