name: 07 - Using Expressions
run-name: 07 - Using Expressions checking
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: "debug desc"
        default: false
        type: boolean
        required: false
jobs:
  expressions-checking:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{inputs.debug}}
        run: |
          echo " input value is true checking actual value ${{inputs.debug}}"
          if [${{github.event_name}}=='push'];then
            echo "this is push event"
          echo "trigger by ${{github.event_name}}"
          echo "branch name : ${{github.ref_name}}"
          echo "Commit Sha: ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"