name: 07 - Using Expressions
run-name: 07 - Using Expressions checking
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: "debug desc"
        type: boolean
        required: false
jobs:
  expressions-checking:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{inputs.debug}}
        run: |
          echo " input value is true checking actual value ${{inputs.debug}}"
          echo "trigger by ${{github.event_name}}"
          echo "branch name : ${{github.ref_name}}"
          echo "Commit Sha: ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"
      - name: "[debug] Print when triggered from main"
        if: ${{inputs.debug}}
        run: |
          echo "I was triggered from main"
      - name: Greeting
        run: |
          echo "Hello Jayaram"
      - name: condition checking
        run: |
          if [ ${{ github.event_name }} == 'push']; then
            echo "coming the trigger event"
          fi
          if [ ${{ github.event_name }} == 'pull_request' ]; then
           echo "This is a pull request event"
          elif [ ${{ github.event_name }} == 'push' ]; then
           echo "This is a push event"
          else
           echo "This is an unknown event"
          fi
