name: 12 - Working with Outputs
run-name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        description: "trigger should receive the following inputs"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build-id.outputs.status }}
      github-path: ${{ steps.github-path.outputs.path }}
      output1: ${{steps.build-id.outputs.output1}}
      output2: ${{steps.build-id.outputs.output2}}
    steps:
      - name: GITHUB_OUTPUT path
        run: |
          echo "$GITHUB_OUTPUT"
      - name: Build
        id: build-id
        run: |
          echo " build status"
          echo "status: ${{ inputs.build-status }}"
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
          echo "output1=value1">> "$GITHUB_OUTPUT"
          echo "output2=value2">> "$GITHUB_OUTPUT"
          echo "mistake=value2" > "$GITHUB_OUTPUT"
          echo "$GITHUB_OUTPUT"
      - name: get the github path and set the output
        id: github-path
        run: |
          echo "get the github path ID"
          echo "path=${{ github.event.ref }}" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: deploy
        run: echo "deploying"
  getPath:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get path
        run: |
          echo "get the status of output: ${{ needs.build.outputs.build-status }}"
          echo "get path form build: ${{ needs.build.outputs.github-path }}"
          echo "checking the val output1: ${{ needs.build.outputs.output1}}"
          echo "checking the val output2: ${{ needs.build.outputs.output2}}"
