name: 12 - Working with Outputs
run-name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        description: "trigger should receive the following inputs"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
       build-status: ${{steps.build-id.outputs.status}}
    steps:
      - name: GITHUB_OUTPUT path
        run: |
          echo "github output path >> $GITHUB_OUTPUT"
      - name: Build
        id: build-id
        run: |
          echo " build status"
          echo "status: status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: deploy
        run: echo "deploying"