name: 14 - Working with Artifacts

run-name : 14 - Working with Artifacts

on:
  workflow_dispatch:
jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/my-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Download cached dependencies
        id: cache-dependency
        uses: actions/cache/restore@v4
        with:
          path: |
             14-artifacts/my-app/node_modules
          key: ${{ runner.os }}-react-dep
      - name: npm install
        if: steps.cache-dependency.outputs.cache-hit != 'true'
        run: npm install
      - name: Unit tests
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4
        id: artifact-id
        with:
          name: react-app
          path: |
            14-artifacts/my-app/build
      - name: atrifact-id
        run:  |
          echo "artifactID: ${{ steps.artifact-id.outputs.artifact-id }}"
  Build:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
           name: react-app
           path: build
