name: 15 - Working with Matrices
run-name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version}}
    runs-on: ubuntu-latest
    strategy:
      #   fail-fast: false # default value is true
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            version: 16.x
          - os: ubuntu-latest
            tag: exprimental
            node-version: 21.x
    steps:
      - name: stepup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail if experimental
        if: ${{ matrix.tag == 'exprimental' }}
        run: |
          exit 1
      - name: sleep 10
        run: |
          sleep 10
      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version}}"
      - name: Upload test results
        run: |
          echo "Uploading test results"
  include-example:
    runs-on: ubuntu-latest
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
    strategy:
      matrix:
        color: [red,green]
        shape: [circle,square]
        size: [small,large]
        include:
          - color: red
            shape: triangle
