name: 16 - Working with Environments
run-name: 16 - Working with Environments ${{ inputs.target-env }}
on:
    workflow_dispatch:
      inputs:
        target-env:
          type: environment
          default: staging
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: checking
        run: |
          echo "checking"
      - name: question
        id: checkid
        run: |
          echo "name=true" >> $GITHUB_ENV
      - name: check if confition
        run: |
         if[[ "${{steps.checkid.outputs.name}}" == 'true' ]]; then
          echo "comming true"
         fi
