name: 16 - Working with Environments
run-name: 16 - Working with Environments ${{ inputs.target-env }}
on:
    workflow_dispatch:
      inputs:
        target-env:
          type: environment
          default: staging
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: checking
        run: |
          echo "checking"
      - name: question
        id: checkid
        run: |
          echo "name=true" >> $GITHUB_OUTPUT
      - name: check if confition
        run: |
         echo "value : ${{ steps.checkid.outputs.name }}"
         if[[ "${{ steps.checkid.outputs.name }}" == "true" ]]; then
          echo "comming true"
         else
          echo "else"
         fi