name: 16 - Working with Environments
run-name: 16 - Working with Environments ${{ inputs.target-env }}
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env}}
    steps:
      - name: echo vars
        run: |
          echo " target value: ${{ vars.MY_ENV_VAR }}"
