name: 16 - Working with Environments
run-name: 16 - Working with Environments
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: stage
    env:
      my-env-value: ${{ vars.MY_ENV_VAR || 'default Value'}}
    steps:
      - name: deploy-staging
        run: |
          echo " Deploying to staging ${{ env.my-env-value }}"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: echo
    steps:
      - name: e2e-test
        run: |
          echo "e2e test running ......"
  deploy-prod:
    runs-on: ubuntu-latest
    needs: e2e-tests
    environment: prod
    env:
      my-env-value: ${{ vars.MY_ENV_VAR || 'default value'}}
    steps:
      - name: Deploy the application
        run: |
          echo "Deploy the application  running ......"

