name:  17 - 2 - Custom Actions - JS
run-name:  17 - 2 - Custom Actions - JS
on:
    workflow_dispatch:
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
