name: 18 - 3 - Reusable Workflows
run-name: 18 - 3 - Reusable Workflows
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: dummy
  e2e-tests:
    needs: deploy
    uses: Jayaramvenkatanarayanan/github-reusable/.github/workflows/e2e.yaml@master
    with:
      access-token: ${{ secrets.GITHUB_TOKEN }}
