name: 19 - 1 - Managing Concurrency
run-name: 19 - 1 - Managing Concurrency
on:
  workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping
        with:
          url: http://www.google.com/
          max-trail: 20
          delay: 5