name: Pull request
run-name: Pull request check with cuncurrecy
on:
  pull_request:

concurrency:
  group: pull_request-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ping-with-concurrency-group:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: sleep 50
        run: |
          sleep 50
      - name: Ping URL
        uses: ./.github/actions/docker-ping
        with:
          url: http://www.google.com/
          trials: 20
          delay: 5
